CB_CHRAR = [
        'Age',
        'BRCA_HRD status',
        'Number of pregnancies',
        'Number of births',
        'P53',
        'ER',
        'P16',
        'Ki67',
        'PS',
        # 'PFS_type'  ## For Cox analysis
        'Pathological type',
        'Stage',
        'Tumor metastasis type',
        'Height',
        'Weight',
        'BMI',
        'Primary surgery hospital',
        'Side reaction',
        'Chronic endocrine history',
        'History of cardiovascular disease', 
        'History of infectious diseases',
        'History of other tumors',
        'Marriage age',
        # 'First/second line and posterior line',  # For post line
        'Second Surgery Hospital',  # For post line
        'Platinum sensitive',
        'Treatment before PARP',
        'PARP type',
        # 'PFS(month)'  ## For Cox analysis
        ]

CLINICAL_CHARA = [
        'Age',
        'Number of pregnancies',
        'Number of births',
        # 'Number of abortions',
        'PS',
        'Pathological type',
        'Stage',
        'Tumor metastasis type',
        'Height',
        'Weight',
        'BMI',
        'Primary surgery hospital',
        # 'Side reaction',
        'Chronic endocrine history',
        'History of cardiovascular disease', 
        'History of infectious diseases',
        'History of other tumors',
        'Marriage age',
        'Platinum sensitive',
        'Treatment regimen',
        'PARPi type',
        # 'First/second line and posterior line',  # For post line
        # 'Second Surgery Hospital',  # For post line
]

CLINICAL_CHARA_FOR_STAT = [
        'Age',
        'Number of pregnancies',
        'Number of births',
        # 'Number of abortions',
        'PS',
        'Pathological type',
        'Stage',
        'Tumor metastasis type',
        'Height',
        'Weight',
        'BMI',
        'Primary surgery hospital',
        # 'Side reaction',
        'Chronic endocrine history',
        'History of cardiovascular disease', 
        'History of infectious diseases',
        'History of other tumors',
        'Marriage age',
        'Platinum sensitive',
        'Treatment before PARP',
        'PARP type',
        'First/second line and posterior line',  # For post line
        'Second Surgery Hospital',  # For post line
]

IMMU_CHARA = [
        'P53',
        'ER',
        'P16',
        'Ki67',
]

BIO_CHARA = [
        'Platelets', 'Ferritin', 'Adenosine Deaminase', 'Chorionic Gonadotropin',
        'Growth Hormone', 'Carbohydrate Antigen-242', 'Carcinoembryonic Antigen',
        'Cancer Antigen 15-3', 'Prostate-Specific Antigen', 'Ceruloplasmin', 
        'Triglycerides', 'Total Bilirubin', 'Fasting Blood Glucose', 'Chloride',
        'Calcium', 'Creatinine', 'N-Acetyl-beta-D-Glucosaminidase',
        'Indirect Bilirubin', 'Bicarbonate', 'Apolipoprotein A1',
        'Total Protein', 'Albumin', 'Beta-2 Microglobulin', 'Cystatin C',
        'Albumin/Globulin Ratio', 'Glutamyl aminotranspeptidase',
        'Alpha-L-Iduronidase', 'Tumor-Specific Growth Factor',
        'Carbohydrate Antigen-199', 'Cancer Antigen 125',
        'Free Prostate-Specific Antigen', 'Alpha-Fetoprotein',
        'Alpha-1 Microglobulin Measurement', 'Homocysteine', 'Globulin',
        'Neuronal-Specific Enolase', 'Iron', 'Total Cholesterol',
        'Direct Bilirubin', 'Total Bile Acids',
        'High-Density Lipoprotein Cholesterol', 'Lipoprotein(a)', 'Phosphorus',
        'Copper', 'Zinc', 'Aspartate Aminotransferase', 'Urea', 'Uric Acid',
        'Apolipoprotein B', 'Lactate Dehydrogenase', 'Low-Density Lipoprotein Cholesterol',
        'High-Sensitivity C-Reactive Protein', 'Alanine Aminotransferase',
        'Alkaline Phosphatase', '5`-Nucleotidase', 'Isoenzymes of Aspartate Aminotransferase',
        'Fibrinogen', 'ABO Blood Type', 'Magnesium', 'Retinol-Binding Protein',
        'Pancreatic Elastase', 'Potassium', 'Sodium', 'Monoamine Oxidase',
        'Ferritin.1', 'Transferrin', 'Prealbumin', 'Rhesus Factor (D)', 'Casts',
        'Fungal Spores', 'Occult Blood (Monoclonal Method)', 'Characteristics',
        'Parasite Eggs', 'Color', 'Fat Globules', 'Pus Cells', 'pH Value',
        'Glucose', 'Turbidity', 'White Blood Cells', 'Hidden Blood',
        'Red Blood Cells', 'Bacteria', 'Nitrites', 'Epithelial Cells',
        'Urobilinogen', 'Protein in Urine', 'Crystals Count', 'Ketones',
        'Bilirubin', 'Specific Gravity of Urine', 'Glycated Hemoglobin',
        'Carbohydrate Antigen-125', 'Thyroid Stimulating Hormone',
        'Free Thyroxine', 'Free Triiodothyronine', 'HIV Antigen/Antibody',
        'Hepatitis C Virus Core Antigen', 'Epstein-Barr Virus EA-IgA',
        'Syphilis Treponema Antibodies (Non-Specific)',
        'Hepatitis A Virus IgM Antibody', 'Hepatitis B Virus Core Antibody',
        'Hepatitis D Virus IgM Antibody', 'Hepatitis E Virus IgM Antibody',
        'Hepatitis E Virus IgG Antibody', 'Epstein-Barr Virus Rta Protein Antibody',
        'Hepatitis B Virus e Antibody', 'Syphilis Treponema Antibodies (Specific)',
        'Hepatitis B Virus Pre-S Antigen', 'Hepatitis B Virus Surface Antibody',
        'Hepatitis B Virus e Antigen', 'Hepatitis C Virus Antibody',
        'Hepatitis B Virus Surface Antigen', 'Hepatitis D Virus Antigen',
        'Hepatitis D Virus IgG Antibody', 'Epstein-Barr Virus Capsid Antigen IgA Antibody',
        'Prothrombin Time', 'D-Dimer', 'Antithrombin III', 'Fibrin Degradation Products',
        'Thrombin Time', 'Fibrinogen Concentration', 'International Normalized Ratio',
        'Activated Partial Thromboplastin Time', 'Absolute Lymphocyte Count',
        'Absolute Eosinophil Count', 'Mean RBC Hemoglobin Concentration',
        'Medium Fluorescent Reticulocyte Ratio', 'Neutrophil Percentage',
        'High Fluorescent Reticulocyte Ratio', 'Absolute Monocyte Count',
        'Platelet Distribution Width', 'Low Fluorescent Reticulocyte Ratio',
        'Lymphocyte Percentage', 'Mean RBC Hemoglobin Content',
        'Absolute Neutrophil Count', 'Absolute Basophil Count',
        'Basophil Percentage', 'Platelet Crit', 'Eosinophil Percentage',
        'Red Blood Cell Distribution Width SD', 'Monocyte Percentage',
        'Absolute Reticulocyte Count', 'Reticulocyte Percentage',
        'Reticulocyte Hemoglobin Content', 'Mean Platelet Volume',
        'Hemoglobin', 'Red Blood Cell Distribution Width CV', 'Hematocrit',
        'Mean Corpuscular Volume', 'Immature Reticulocyte Fraction',
        'Human Epididymis Protein 4', 'Squamous Cell Carcinoma Antigen',
        'Ovarian Malignancy Risk Value (Postmenopausal)',
        'Ovarian Malignancy Risk Value (Premenopausal)',
        'Red Blood Cell Antibody Screen', 'Rhesus Factor (C)',
        'Specific Blood Type', 'Rhesus Factor (E)']